### ISSUE TITLE
IEMA error

### ISSUE THREAD

**Issue by RhayH** [datazoompuc/datazoom.amazonia#126]
Olá, o pacote do IEMA está dando erro.

**Comment by FredieDidier** [comment]
Olá, boa tarde. Teria como o senhor(a) mandar exatamente qual foi o problema?
Nós testamos o IEMA e por aqui está funcionando corretamente

**Comment by RhayH** [comment]
Olá! Então, o erro é o seguinte: Error in loadNamespace(x) : there is no package called ‘googledrive’

**Comment by FredieDidier** [comment]
Olá, bom dia. Tenta instalar o pacote "googledrive" no seu R. Após isso, acredito que irá funcionar

**Comment by RhayH** [comment]
Ainda continua sem funcionar.
instalei, adicionei na library, reinstalei tudo de novo. O erro que dá agora é 

> data <- load_iema(dataset = "iema", raw_data = FALSE,geo_level = "municipality", language = "pt")
Error in load_iema(dataset = "iema", raw_data = FALSE, geo_level = "municipality",  : 
  could not find function "load_iema"

Pra vc está funcionando perfeitamente? Quais são todas as suas linhas de código para eu copiar aqui?

**Comment by FredieDidier** [comment]
Oi, tenta fazer o install github e dps roda library (datazoom.amazonia). Aí, roda a função do IEMA e me diz se foi

**Comment by gnjardim** [comment]
Parece ter sido resolvido, @RhayH favor reabrir caso o problema persista.
