### ISSUE TITLE
Error in Download - IBAMA

### ISSUE THREAD

**Issue by fernandanevesw** [datazoompuc/datazoom.amazonia#137]
Hello,
Occurred an error while downloading the following data:

# Download treated collected fines data from "BA"
data <- load_ibama(dataset = "collected_fines", raw_data = FALSE,
                   states = "BA", language = "pt")

Error in `dplyr::mutate()`:
! Problem while computing `municipio = dplyr::case_when(...)`.
Caused by error in `value[[i]]`:
! índice fora de limites

**Comment by gnjardim** [comment]
Fixed on PR #179
