### ISSUE TITLE
IPS README example #2 error

### ISSUE THREAD

**Issue by lauratregadas** [datazoompuc/datazoom.amazonia#146]
As I tried to run the available code, I encountered the following error message:

Error in `dplyr::bind_cols()`:
! Can't recycle `..1` (size 3865) to match `..2` (size 773).
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/vctrs_error_incompatible_size>
Error in `dplyr::bind_cols()`:
! Can't recycle `..1` (size 3865) to match `..2` (size 773).
---
Backtrace:
 1. datazoom.amazonia::load_ips(...)
 2. dplyr::bind_cols(year, df)
 5. vctrs::vec_cbind(!!!dots, .name_repair = .name_repair)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/vctrs_error_incompatible_size>
Error in `dplyr::bind_cols()`:
! Can't recycle `..1` (size 3865) to match `..2` (size 773).
---
Backtrace:
    ▆
 1. ├─datazoom.amazonia::load_ips(...)
 2. │ └─dplyr::bind_cols(year, df)
 3. │   ├─dplyr:::fix_call(vec_cbind(!!!dots, .name_repair = .name_repair))
 4. │   │ └─base::withCallingHandlers(...)
 5. │   └─vctrs::vec_cbind(!!!dots, .name_repair = .name_repair)
 6. └─vctrs::stop_incompatible_size(...)
 7.   └─vctrs:::stop_incompatible(...)
 8.     └─vctrs:::stop_vctrs(...)
 9.       └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_call(call))
> 

I tried running the code with multiple time periods and the issue only happened when trying to cover three or more years.

**Comment by gnjardim** [comment]
Hi @lauratregadas could you provide more information on that issue? What was the exact command you used?

**Comment by lauratregadas** [comment]
Absolutely!

`install.packages("devtools", type = "win.binary")
library(devtools)
install_github("datazoompuc/datazoom.amazonia")
library(datazoom.amazonia)`

# Download raw data from 2014
#raw data is only available in portuguese
`data <- load_ips(dataset = "all", raw_data = TRUE, time_period = 2014, language = "pt")`

# Download treated deforest data from both year (time_period = 2014:2018) in english
#runs error
`data <- load_ips(dataset = "deforest", raw_data = FALSE,
                 time_period = 2014:2018)
`

**Comment by gnjardim** [comment]
Example was changed in previous PR, added check on PR #173
