### ISSUE TITLE
Problem installing from Github

### ISSUE THREAD

**Issue by ArthurLins-code** [datazoompuc/datazoom.amazonia#153]
Hello! I was trying to download the package from Github with the specified path on the READ.me file. But everytime I ask it to do it, a message appears saying that 2 packages have more recent versions (purrr and curls), after I ask to either update or not, the installation of the desired package starts, but it never works (I've tried several time already). While also showing this message:

![image](https://user-images.githubusercontent.com/110439563/194887966-430d6769-38e4-4ac4-9c47-65ebf0d5de1d.png)

**Comment by gnjardim** [comment]
In this case we suggest trying to install each required package separately and then trying to download `datazoom.amazonia` again. In the case of the package `devtools`, you're also required to install [Rtools](https://cran.r-project.org/bin/windows/Rtools/) if you are using a Windows machine.
