### ISSUE TITLE
Inconvenience with size - PEVS, COMEX, TerraClimate, BACI

### ISSUE THREAD

**Issue by AntonioBergallo** [datazoompuc/datazoom.amazonia#155]
### Context

The datasets used are listed in the issue name.

### Code

PEVS
```r
data <- load_pevs(dataset = 'pevs_forest_crops', 
                  raw_data = TRUE, 
                  geo_level = "municipality", 
                  time_period = 2012:2013, 
                  language = "eng")
```

COMEX
```r
load_br_trade(dataset = "comex_import_prod",
                      raw_data = FALSE, 
                      time_period = 1997:2021)
```

TerraClimate
```r
max_temp <- load_climate(dataset = "max_temperature", time_period = 2000:2020
```

BACI
```r
clean_baci <- load_baci(dataset = "HS92", raw_data = FALSE, time_period = 2016,
                        language = "pt")
```

### Goals and Expectations

When running these examples, the user expects to receive a dataframe containing treated data or a list containing raw data. When coming across this kind of problem, there is no output, as the download isn´t finished.

### Suggestions!

All the suggestions made consist on restraining the range of time or filtering for a less especific geographic level. They do not solve the problem, but are consistent and clever ways of overcoming the inconvenience. For the BACI example though, this is not achievable, as the data is already restrained to a year and there is no geographic level option. 

**PEVS (Laura)**

geo_level = "municipality" makes database too big to run. I found that setting geo_level to "region" made a good example

**COMEX (Victor)**

Year span reduced to 2 years in the example.

```r
load_br_trade(dataset = "comex_import_prod", raw_data = FALSE, time_period = 2020:2021)
```
**TerraClimate (Arthur)**

```r
max_temp <- load_climate(dataset = "max_temperature", time_period = 2000:2002)
```

**Comment by IgorRigolon** [comment]
Recommendations have been followed: time spans in the examples are now shorter and `geo_level = "municipality"` was avoided,
