### ISSUE TITLE
Inconvenience with <LOAD_DATASUS> - <DATASUS>

### ISSUE THREAD

**Issue by AntonioBergallo** [datazoompuc/datazoom.amazonia#159]
# Argument "state" is not filtering correctly

### Context

Package was downloades from github via DevTools

### Code

```r
data <- load_datasus(dataset = "datasus_sim_do",
                     time_period = c(2020),
                     states = "RJ",
                     raw_data = FALSE)

```

### Goals and Expectations

I was expecting to download mortality data exclusively from Rio, however, it loaded from cities outside the state, such as Manaus and Belém.

**Comment by gnjardim** [comment]
The argument `states` is related to residents of the corresponding state, but the death could occur somewhere else. The columns "code_muni" and "name_muni" are defined based on where the death occured. 

This should be better documented.
