### ISSUE TITLE
Expansão de <LOAD_ANEEL> e <LOAD_EPE>

### ISSUE THREAD

**Issue by VictorHugoTerziani** [datazoompuc/datazoom.amazonia#165]
Das 6 bases sugeridas pelo CPI para serem utilizadas nas visualizações de energia, 4 já estão no datazoom.amazonia.

load_aneel carrega os datasets "energy_development_budget" e "energy_generation".
load_epe carrega os datasets "energy_consumption_per_class" e "national_energy_balance".

As duas bases que ainda não estão incluídas são 
1) "Anuário Estatístico de Energia Elétrica" 
2) "Relação de Empreendimentos de Geração Distribuida"
cujos links para achá-las, respectivamente, são:
1) https://www.epe.gov.br/pt/publicacoes-dados-abertos/publicacoes/anuario-estatistico-de-energia-eletrica
2) https://dadosabertos.aneel.gov.br/dataset/relacao-de-empreendimentos-de-geracao-distribuida

Segundo a lógica sendo usada nas funções, a primeira base seria inserida como um novo dataset em load_epe e a segunda base seria inserida como um novo dataset em load_aneel.
Mais informações sobre essas bases podem ser encontradas no nosso drive, seguindo os caminhos:

Data Zoom > Sites > Site - Data Zoom Amazônia > Posts > Energia - Data Zoom e CPI - AMZ exporta energia

Data Zoom > Sites > Site - Data Zoom Amazônia > Posts > Energia - Data Zoom e CPI - GeraçãoDistribuída

**Comment by VictorHugoTerziani** [comment]
Concordo, @gnjardim. Algumas tabelas da base da EPE trazem informações interessantes (as relacionadas ao Brasil), mas a formatação é péssima e não consistente (formatação e ordem das tabelas muda a cada lançamento). Acredito que o trabalho de incorporar a base no pacote e mante-la ao longo do tempo não compense.

**Comment by gnjardim** [comment]
Pois é, e são todos dados mais agregados do que a gente costuma disponibilizar. Não sei se vejo tanto valor em ter eles dentro do pacote
