### ISSUE TITLE
Suggestion: picking datasets from keyboard input

### ISSUE THREAD

**Issue by IgorRigolon** [datazoompuc/datazoom.amazonia#168]
## Description of the problem

When I want to use some function (I'll use `load_aneel` as a running example), I find it extremely satisfactory to just type

```
df <- load_aneel()
```

and instantly get a neat result. Because we have default options that we assume most users already want (e.g. `raw_data = FALSE` and `language = "eng"`), this is in fact possible for many functions. But when functions have many equally important datasets, the user must choose one. So my code above is met with

```
Error in load_aneel() : argument "dataset" is missing, with no default
```

To use the function, one is forced to copy/paste or -- god forbid -- manually type some long string of characters, such as `"energy_development_budget"` or `"energy_generation"`.

## Suggestion

In the README section for ANEEL, we already have this ready

---

**Options:**

1.  **dataset**: there are two choices:
    -   `"energy_development_budget"`: government spending towards
        energy sources
    -   `"energy_generation"`: energy generation by entity/corporation
    ...

---

So what if I typed

```
df <- load_aneel()
```

and got something like this in the console

```
No dataset selected. Type a number to pick one

1 - "energy_development_budget": government spending towards energy sources

2 - "energy_generation": energy generation by entity/corporation
```

Not sure how to implement it in a concise way that works for all functions, but it would be pretty cool

**Comment by gnjardim** [comment]
I agree that it would be an interesting feature, but I have concerns regarding the reproducibility of codes that follow this approach. @FranciscoCavalcanti any thoughts on this?
