### ISSUE TITLE
Citation template inclusion

### ISSUE THREAD

**Issue by lauratregadas** [datazoompuc/datazoom.amazonia#177]
Data Zoom now has a citation template. 

Please include it in the package as a message. It should show up when the user calls the package. If you think of any other situations where it would be it interesting for the message to pop-up, feel free to include the template there too.

Written format:
Data Zoom (2023). Data Zoom: Simplifying Access To Brazilian Microdata.
https://www.econ.puc-rio.br/datazoom/english/index.html

BibTex format:
`https://drive.google.com/file/d/1Nyuw9LANR78not9O3Ssh-OEP-b5y7RN1/view?usp=share_link`
Please copy and paste this link on your browser's search bar. I couldn't upload the .tex file to GitHub because it doesn't support this format.

**Comment by gnjardim** [comment]
Solved on #178
