### ISSUE TITLE
Inconvenience with <load_pam> - <all_crops> - Missed micro region and download not continuous

### ISSUE THREAD

**Issue by VictorHugoTerziani** [datazoompuc/datazoom.amazonia#184]
# Very brief description of the problem

- When using the load_pam function, a message was sent into the console, asking for a report to the developers of the package.
- The downloads at the meso/micro region are not continuous. (Defining what I mean by that below)

### Context

- The package being used is from github. 
- The PC being used is the PUC's computer fom DE's laboratory.

### Code
The following line of code was written:

```r
pam_municipality_all_crops= load_pam(dataset = 'all_crops', raw_data = FALSE, 'municipality', 1974:2021, language = "pt")
```

The following message was retrieved from the computer console after a few days of running the code:

```
1 missed API requests at the Microregion level.
                              Please report this problem to package developers...
```

### Goals, Expectations and Problems

I was expecting to download the data of all crops at the municipality level from the time span selected, 
But the message popped up.

There is also the inconvenience that the download is stopping at, for example, the mesoregion 39 of 104 (It is happening to many mesoregions or microregions in many steps of the download). And by "not continuous", I mean that I have to press the 'esc' button for it to continue to download. For instance, last weekend, the dowload was stagnated at the 39th mesoregion of a given year (I don't know which year) from friday to tuesday. After trying to terminate the download process and pressing 'esc', the download continued for the 40th mesoregion of that given year.

### Suggestions!

I see that the missed microregion's error message comes from the Sidra download function.
The message came from download.R's line 264. 

I don't have any suggestions about the "non-continuity" of the download.

**Comment by gnjardim** [comment]
There's usually not much we can do regarding those issues, since they are mainly caused by SIDRA API. I suggest you try to download those specific regions again, and reopen this issue in case it persists.
