### ISSUE TITLE
MapBiomas collection is not transparent & adding option to select version would be very useful

### ISSUE THREAD

**Issue by sam-a-levy** [datazoompuc/datazoom.amazonia#189]
When using `load_mapbiomas()` it is not obvious which MapBiomas collection is being used although you can tell for some layers by looking at the name of the downloaded file. Adding a warning that states which collection is being provided would be very helpful.

Additionally, it would very, very useful to add an option allowing the user to select which MapBiomas version is being used.

**Comment by gnjardim** [comment]
Thank you very much for your suggestion, I've implemented this message stating the MapBiomas collection being used on PR #190.

Currently, we don't have plans to support older versions of MapBiomas. However, we encourage contributions from our users and would be glad to help.

**Comment by sam-a-levy** [comment]
Great, thank you!

Re supporting older versions of MapBiomas - I believe they are all still held on gdrive/googleAPI/amazonaws, e.g. for coverage/transitions:

- Collection 5: https://mapbiomas-br-site.s3.amazonaws.com/Estat%C3%ADsticas/Dados_Cobertura_MapBiomas_5.0_UF-MUN_SITE_v2.xlsx
- Collection 6: https://drive.google.com/file/d/1RT7J2jS6LKyISM49ctfRO31ynJZXX_TY/view?usp=sharing
- Collection 7: https://storage.googleapis.com/mapbiomas-public/brasil/downloads/1-tabela-geral-col7-mapbiomas-biomas-municipio-final.xlsx
- Collection 7.1: https://storage.googleapis.com/mapbiomas-public/brasil/coverage/col71/statistics/TABELA-GERAL-COL71-MAPBIOMAS-BIOMASxMUNICIPIOS-v2.xlsx

So I would imagine that adding a small section of code that chooses the link based on the version & then accounts for the minor changes between versions that you must have already dealt with when updating the code (e.g. var `geo_code` was renamed `feature_id` between collection 6 & 7).

However, that said - I understand that the most important feature is to provide the most up-to-date version and very much appreciate all the work you have done (incl. to make the version clearer). Offering users control of the collection used would definitely assist in reproducing results from previous analyses, but is not the most pressing issue.
