### ISSUE TITLE
Error in load_iema

### ISSUE THREAD

**Issue by giuliaimbu** [datazoompuc/datazoom.amazonia#203]
The file AMAZONIA_nao_atendidos.xlsx doesn't appear anywhere in the computer when it's downloaded.

```r
> data <- load_iema(raw_data = FALSE)
Please follow the steps from `googledrive` package to download the data. This may take a while.
In case of authentication errors, run vignette("GOOGLEDRIVE").
Auto-refreshing stale OAuth token.
File downloaded:
• AMAZONIA_nao_atendidos.xlsx <id: 10JMRtzu3k95vl8cQmHkVMQ9nJovvIeNl>
Saved locally as:
• C:\Users\Giulia\AppData\Local\Temp\RtmpwxQqsv\file1b101bea593f.xlsx
```

When I click on the link above, the following message appears on the screen: "'C:\Users\Giulia\AppData\Local\Temp\RtmpwxQqsv\file1b101bea593f.xlsx' does not exist".

**Comment by IgorRigolon** [comment]
This file is only saved as a temporary file (notice how it was in the /Temp/ folder). Once the data is read, it is deleted, and it's not meant to be saved to your computer. The output of the function was saved to the `data` object as a dataframe when I tested it.
