### ISSUE TITLE
Error in load_ibama_wrapper_fines_rawfalse_states

### ISSUE THREAD

**Issue by giuliaimbu** [datazoompuc/datazoom.amazonia#226]
We can modify the code to loop through the specified states and load the data for each state separately:

```r
load_ibama_wrapper_fines_rawfalse_states <- function() {
  states_to_load <- c("AC", "AM")  # Specify the states you want to load
  results <- list()

  for (state in states_to_load) {
    tryCatch({
      message <- load_ibama(
        dataset = "distributed_fines",
        raw_data = FALSE,
        states = state,
        language = "pt"
      )
      results[[state]] <- message
    }, error = function(e) {
      results[[state]] <- paste("Error for state", state, ":", e$message)
    })
  }
  
  return(results)
}

```

In this modified version, we create an empty list called results to store the results for each state. The function iterates over the states_to_load vector and uses tryCatch to handle any errors that might occur during the data loading process for each state. The results for each state, including success messages or error messages, are stored in the results list.

After processing all the specified states, the function returns the results list, which will contain the success or error messages for each state. You can then inspect the results to see if any specific states encountered errors while loading the data.

To use this function, call load_ibama_wrapper_fines_rawfalse_states() as before:

```r
results <- load_ibama_wrapper_fines_rawfalse_states()
```

Now, results will contain messages for each state, indicating whether the data was loaded successfully or if an error occurred.

**Comment by IgorRigolon** [comment]
I found two bugs in the function:

***

First, for all datasets, calling a vector of states doesn't work.

``` r
datazoom.amazonia::load_ibama(dataset = "distributed_fines", 
    raw_data = FALSE, states = c("AC", "AM"), language = "pt")
#> Error in if (states == "all") {: the condition has length > 1
```

<sup>Created on 2023-11-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This should be very easy to fix. Say you want `states = c("AC", "AM")`. In line 63, there's the following code:

```
  if (states == "all") {
    param$states <- c("RO", "AC", "AM", "RR", "PA", "AP", "TO", "MA", "PI", "CE", "RN",
                      "PB", "PE", "AL", "SE", "BA", "MG", "ES", "RJ", "SP", "PR", "SC",
                      "RS", "MS", "MT", "GO", "DF")
  }
```

This is meant to be a helpful shortcut for users to download all states. But the `states == "all"` condition is the same as `"c("AC", "AM")" == "all"`, which returns the vector `c(FALSE, FALSE)` (you're comparing a vector and a string). If we change the code to

```
 if (any(states == "all"))
...
```

it should work fine.

***

The second error has to do with the `municipalities` dataset, which we call in the function. I don't know what exactly is wrong though, we also call `datazoom.amazonia::municipalities` the same way in other functions.

``` r
datazoom.amazonia::load_ibama(dataset = "distributed_fines", 
    raw_data = FALSE, states = c("AC"), language = "pt")
#> Downloading AC (1 out of 1)
#> Error in datazoom.amazonia::load_ibama(dataset = "distributed_fines", : objeto 'municipalities' não encontrado
```

<sup>Created on 2023-11-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
