### ISSUE TITLE
Installation need exact version of R?

### ISSUE THREAD

**Issue by reichaves** [datazoompuc/datazoom.amazonia#80]
Please I have R - R version 4.1.2 (2021-11-01)
I tried installing datazoom.amazonia:

> install.packages("datazoom.amazonia")
Warning in install.packages :
  package ‘datazoom.amazonia’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

Do I need to update my R?

**Comment by FredieDidier** [comment]
Olá, boa tarde.

O senhor precisa instalar primeiro este pacote: devtools :: install_github( " ipeaGIT/geobr " , subdir  =  " r-package " ) .
Depois de instalá-lo , basta instalar: devtools :: install_github( " datazoompuc/datazoom.amazonia " )

**Comment by FranciscoCavalcanti** [comment]
Dear @reichaves,

The CRAN version of the package is inactive, unfortunately. Therefore, we recommend using the development version which should work without any issues.

For that, you first need to install the **devtools** and **geobr** package.

`install.packages("devtools")`
`devtools::install_github("ipeaGIT/geobr", subdir = "r-package").`

Then install datazoom.amazonia.

`devtools::install_github("datazoompuc/datazoom.amazonia")`

Let me know if it works.

**Comment by reichaves** [comment]
Thanks. Worked

**Comment by pedrorenanm** [comment]
Hello guys,

I tried the solution cited for @FranciscoCavalcanti and worked. But, when I tried to read the IPS database I got this error message: 

##########################################################################################

> datazoom.amazonia::load_ips(raw_data = F,language = "Portuguese",time_period = 2014:2018)

trying URL 'http://www.ipsamazonia.org.br/assets/IPS_Tabela_Completa-8bb3b841e46c8fb17b0331d8ea92bef3.xlsx'
Error in utils::download.file(url = path, destfile = temp, mode = "wb") : 
  cannot open URL 'http://www.ipsamazonia.org.br/assets/IPS_Tabela_Completa-8bb3b841e46c8fb17b0331d8ea92bef3.xlsx'
In addition: Warning message:
In utils::download.file(url = path, destfile = temp, mode = "wb") :
  cannot open URL 'http://www.ipsamazonia.org.br/assets/IPS_Tabela_Completa-8bb3b841e46c8fb17b0331d8ea92bef3.xlsx': HTTP status was '503 Service Unavailable'

##########################################################################################

I didn't get the same error when I tried to download the "mapbiomas" database

##########################################################################################

> datazoom.amazonia::load_mapbiomas(dataset = "mapbiomas_deforestation_regeneration",
+             geo_level = "municipality",raw_data = T)
trying URL 'https://mapbiomas-br-site.s3.amazonaws.com/Estat%C3%ADsticas/BD-DESM_e_REG_COL5_V8h__SITE.xlsx'
Content type '' length 2940452 bytes (2.8 MB)
downloaded 2.8 MB

# A tibble: 1,891 x 44
      id codigobioma bioma    uf       cod_comb cod_tipo_mudanca_n2 cod_tipo_mudanc~
   <dbl>       <dbl> <chr>    <chr>       <dbl>               <dbl>            <dbl>
 1     1           1 Amazonia Rondonia      115                   1                1
 2     2           1 Amazonia Rondonia      124                   1                1
 3     3           1 Amazonia Rondonia      130                   1                1
 4     4           1 Amazonia Rondonia      141                   1                1
 5     5           1 Amazonia Rondonia      203                   2                2
 6     6           1 Amazonia Rondonia      204                   2                2
 7     7           1 Amazonia Rondonia      303                   3                2
 8     8           1 Amazonia Rondonia      304                   3                2
 9     9           1 Amazonia Rondonia      312                   3                2
10    10           1 Amazonia Rondonia      403                   4                4
# ... with 1,881 more rows, and 37 more variables: cod_classe_des_ou_reg <dbl>,
#   tipo_mudanca_nivel1 <chr>, tipo_mudanca_nivel2 <chr>, cobertura_nivel_1 <chr>,
#   cobertura_nivel_2 <chr>, cobertura_nivel_3 <chr>, cobertura_nivel_4 <chr>,
#   x1988 <dbl>, x1989 <dbl>, x1990 <dbl>, x1991 <dbl>, x1992 <dbl>, x1993 <dbl>,
#   x1994 <dbl>, x1995 <dbl>, x1996 <dbl>, x1997 <dbl>, x1998 <dbl>, x1999 <dbl>,
#   x2000 <dbl>, x2001 <dbl>, x2002 <dbl>, x2003 <dbl>, x2004 <dbl>, x2005 <dbl>,
#   x2006 <dbl>, x2007 <dbl>, x2008 <dbl>, x2009 <dbl>, x2010 <dbl>, ...

##########################################################################################

Does someone know how to access the IPS database through this package?

**Comment by FredieDidier** [comment]
Olá, bom dia. Acabei de verificar aqui e parece que o site do IPS está em manutenção (fora do ar). Por isso que não está funcionando.

**Comment by FredieDidier** [comment]
Hi, I just verified this and it turns out the IPS website is under maintenance. That is why it is not working

**Comment by pedrorenanm** [comment]
Thanks, @FredieDidier. I'll be waiting for the IPS website returns and send feedback here :)

**Comment by gnjardim** [comment]
Parece ter sido resolvido, favor reabrirem caso o problema persista.
