### ISSUE TITLE
Dataframe without column names

### ISSUE THREAD

**Issue by reichaves** [datazoompuc/datazoom.amazonia#99]
After this command for the dataset "areas_embargadas", the generated dataframe does not have the column names:

ibama <- load_ibama(dataset = "areas_embargadas", raw_data = TRUE, 
                   language = "pt", legal_amazon_only = FALSE)

**Comment by luizguilhermelopesm** [comment]
Hi, @reichaves!
Have you tried updating the package? Just run `devtools::install_github("datazoompuc/datazoom.amazonia")` again. Recently our team worked on some minor fixes in load_ibama( ), and the function was updated. Try doing that and let us know if it works!

**Comment by reichaves** [comment]
It works, thanks
